---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Deploys an api behind cloudfront that dumps headers.

Resources:
    ReturnHeadersFunction:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName: list-instances-api
          CodeUri: dist/
          Handler: handler.handler
          Runtime: python3.8
          Timeout: 300
          Tracing: Active
          AutoPublishAlias: live
          DeploymentPreference:
              #Change to Canary10Percent5Minutes after developemnt
              Type: AllAtOnce
          MemorySize: 128
          Events:
            APIGateway:
              Type: Api
              Properties:
                Path: /
                Method: GET

      Distro:
        Type: AWS::CloudFront::Distribution
        Properties:
          DistributionConfig:
            DefaultCacheBehavior: DefaultCacheBehavior     # required
            Enabled: True
            HttpVersion: http2
            Origins:                # required, list of Origin
              -
                CustomOriginConfig:
                  CustomOriginConfig
                DomainName: 554jrr4221.execute-api.us-east-1.amazonaws.com
                Id: 1
                OriginPath: /Prod
            PriceClass: PriceClass_100
