---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Deploys an api behind cloudfront that dumps headers.

Resources:
    ReturnHeadersFunction:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName: list-headers
          CodeUri: dist/
          Handler: handler.handler
          Runtime: python3.8
          Timeout: 29
          AutoPublishAlias: live
          DeploymentPreference:
              #Change to Canary10Percent5Minutes after developemnt
              Type: AllAtOnce
          MemorySize: 128
          Events:
            APIGateway:
              Type: Api
              Properties:
                Path: /
                Method: GET
                RestApiId: !Ref API
    API:
      Type: AWS::Serverless::Api
      Properties:
        Cors: "'headers.owen.dev'"
        StageName: Prod

    Cert:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: headers.owen.dev
        ValidationMethod: DNS

    Distro:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - headers.owen.dev
          ViewerCertificate:
            AcmCertificateArn: !Ref Cert
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: 1
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            MaxTTL: 86400
            DefaultTTL: 86400
            ForwardedValues:
              Headers:
                - CloudFront-Viewer-City
                - CloudFront-Viewer-Country
                - CloudFront-Viewer-Country-Name
                - CloudFront-Viewer-Country-Region
                - CloudFront-Viewer-Country-Region-Name
                - CloudFront-Viewer-Latitude
                - CloudFront-Viewer-Longitude
                - CloudFront-Viewer-Metro-Code
                - CloudFront-Viewer-Postal-Code
                - CloudFront-Viewer-Time-Zone
              QueryString: False
          Enabled: True
          HttpVersion: http2
          Origins:
            -
              CustomOriginConfig:
                HTTPSPort: 443
                OriginKeepaliveTimeout: 1
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
              DomainName: !Sub
                - '${APIResourceID}.execute-api.${AWS::Region}.amazonaws.com'
                -
                  APIResourceID: !GetAtt API.RootResourceId
              Id: 1
              OriginPath: /Prod
          PriceClass: PriceClass_100
